//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace His_Pos.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("His_Pos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 打卡及請假 的當地語系化字串。
        /// </summary>
        internal static string Attend {
            get {
                return ResourceManager.GetString("Attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇調劑案件(案件分類) 的當地語系化字串。
        /// </summary>
        internal static string CaseCategoryNull {
            get {
                return ResourceManager.GetString("CaseCategoryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的當地語系化字串。
        /// </summary>
        internal static string ChronicAdjustCaseId {
            get {
                return ResourceManager.GetString("ChronicAdjustCaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 慢性病連續處方箋需填寫連續處方可調劑次數 的當地語系化字串。
        /// </summary>
        internal static string ChronicDeliveryTimesNull {
            get {
                return ResourceManager.GetString("ChronicDeliveryTimesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 慢性病連續處方箋需填寫連續處方箋調劑序號 的當地語系化字串。
        /// </summary>
        internal static string ChronicSequenceNull {
            get {
                return ResourceManager.GetString("ChronicSequenceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上下班打卡 的當地語系化字串。
        /// </summary>
        internal static string ClockIn {
            get {
                return ResourceManager.GetString("ClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 基本資料管理 的當地語系化字串。
        /// </summary>
        internal static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ..\Images\Done.png 的當地語系化字串。
        /// </summary>
        internal static string declareDone {
            get {
                return ResourceManager.GetString("declareDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ..\Images\Error.png 的當地語系化字串。
        /// </summary>
        internal static string declareError {
            get {
                return ResourceManager.GetString("declareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ..\Images\SubmitProgress.png 的當地語系化字串。
        /// </summary>
        internal static string declareNone {
            get {
                return ResourceManager.GetString("declareNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 非藥事居家照護或協助辦理門診戒菸計畫且直接交付指示用藥、提供「戒菸個案追蹤」或「戒菸衛教暨個案管理」者，需填寫就醫科別 的當地語系化字串。
        /// </summary>
        internal static string DivisionNull {
            get {
                return ResourceManager.GetString("DivisionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 員工管理 的當地語系化字串。
        /// </summary>
        internal static string EmployeeManage {
            get {
                return ResourceManager.GetString("EmployeeManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處方作業 的當地語系化字串。
        /// </summary>
        internal static string hisPrescription {
            get {
                return ResourceManager.GetString("hisPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫診治醫師代號 的當地語系化字串。
        /// </summary>
        internal static string hisPrescriptionDecDoctorIdNullMessage {
            get {
                return ResourceManager.GetString("hisPrescriptionDecDoctorIdNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處方登錄 的當地語系化字串。
        /// </summary>
        internal static string hisPrescriptionDeclare {
            get {
                return ResourceManager.GetString("hisPrescriptionDeclare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處方查詢 的當地語系化字串。
        /// </summary>
        internal static string hisPrescriptionInquire {
            get {
                return ResourceManager.GetString("hisPrescriptionInquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 非藥事居家照護或協助辦理門診戒菸計畫且直接交付指示用藥、提供「戒菸個案追蹤」或「戒菸衛教暨個案管理」者，原處方機構代號不可為&quot;N&quot; 的當地語系化字串。
        /// </summary>
        internal static string InstitutionIdError {
            get {
                return ResourceManager.GetString("InstitutionIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請假申請 的當地語系化字串。
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 櫃位管理 的當地語系化字串。
        /// </summary>
        internal static string LocationManage {
            get {
                return ResourceManager.GetString("LocationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 供應商管理 的當地語系化字串。
        /// </summary>
        internal static string ManufactoryManage {
            get {
                return ResourceManager.GetString("ManufactoryManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 藥品頻率管理 的當地語系化字串。
        /// </summary>
        internal static string MedFrequencyManage {
            get {
                return ResourceManager.GetString("MedFrequencyManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 非藥事居家照護或協助辦理門診戒菸計畫且直接交付指示用藥、提供「戒菸個案追蹤」或「戒菸衛教暨個案管理」者，需填寫原處方機構案件分類 的當地語系化字串。
        /// </summary>
        internal static string MedicalCaseNull {
            get {
                return ResourceManager.GetString("MedicalCaseNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 慢性病連續處方箋需填寫原處方就醫序號 的當地語系化字串。
        /// </summary>
        internal static string MedicalNumberNull {
            get {
                return ResourceManager.GetString("MedicalNumberNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日劑藥費且為西醫一般案件，給藥日份不得超過3天 的當地語系化字串。
        /// </summary>
        internal static string MedicineDaysOutOfRange {
            get {
                return ResourceManager.GetString("MedicineDaysOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一般處方箋給藥日份不得超過7天 的當地語系化字串。
        /// </summary>
        internal static string MedicineDaysOutOfRange_1_7 {
            get {
                return ResourceManager.GetString("MedicineDaysOutOfRange_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增盤點 的當地語系化字串。
        /// </summary>
        internal static string NewStockTaking {
            get {
                return ResourceManager.GetString("NewStockTaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 診治醫生未填寫 的當地語系化字串。
        /// </summary>
        internal static string noDoctorMsg {
            get {
                return ResourceManager.GetString("noDoctorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 釋出院所未填寫 的當地語系化字串。
        /// </summary>
        internal static string noInstitutionMsg {
            get {
                return ResourceManager.GetString("noInstitutionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處方未填寫 的當地語系化字串。
        /// </summary>
        internal static string noMedicineMsg {
            get {
                return ResourceManager.GetString("noMedicineMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇調劑日期 的當地語系化字串。
        /// </summary>
        internal static string noTreatmentDateMsg {
            get {
                return ResourceManager.GetString("noTreatmentDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 非藥事居家照護者，需填寫就醫日期 的當地語系化字串。
        /// </summary>
        internal static string PrescriptionDateNull {
            get {
                return ResourceManager.GetString("PrescriptionDateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 測試啦 的當地語系化字串。
        /// </summary>
        internal static string PrescriptionDec2 {
            get {
                return ResourceManager.GetString("PrescriptionDec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處理單管理 的當地語系化字串。
        /// </summary>
        internal static string ProductPurchase {
            get {
                return ResourceManager.GetString("ProductPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處理單紀錄 的當地語系化字串。
        /// </summary>
        internal static string ProductPurchaseRecord {
            get {
                return ResourceManager.GetString("ProductPurchaseRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品類別管理 的當地語系化字串。
        /// </summary>
        internal static string ProductTypeManage {
            get {
                return ResourceManager.GetString("ProductTypeManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 非藥事居家照護或協助辦理門診戒菸計畫且直接交付指示用藥、提供「戒菸個案追蹤」或「戒菸衛教暨個案管理」者，需填寫原處方服務機構之特定治療項目代號 的當地語系化字串。
        /// </summary>
        internal static string SpecialTreatmentCodeNull {
            get {
                return ResourceManager.GetString("SpecialTreatmentCodeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存管理 的當地語系化字串。
        /// </summary>
        internal static string StockManage {
            get {
                return ResourceManager.GetString("StockManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存查詢 的當地語系化字串。
        /// </summary>
        internal static string StockSearch {
            get {
                return ResourceManager.GetString("StockSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存盤點 的當地語系化字串。
        /// </summary>
        internal static string StockTaking {
            get {
                return ResourceManager.GetString("StockTaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存盤點紀錄 的當地語系化字串。
        /// </summary>
        internal static string StockTakingRecord {
            get {
                return ResourceManager.GetString("StockTakingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 非藥事居家照護者，至少需填寫一項國際疾病分類碼 的當地語系化字串。
        /// </summary>
        internal static string TreatmentCodeNull {
            get {
                return ResourceManager.GetString("TreatmentCodeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排班管理 的當地語系化字串。
        /// </summary>
        internal static string WorkScheduleManage {
            get {
                return ResourceManager.GetString("WorkScheduleManage", resourceCulture);
            }
        }
    }
}
