//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace His_Pos.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("His_Pos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇調劑案件
        /// 的當地語系化字串。
        /// </summary>
        internal static string AdjustCaseError {
            get {
                return ResourceManager.GetString("AdjustCaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫調劑日期
        /// 的當地語系化字串。
        /// </summary>
        internal static string AdjustDateError {
            get {
                return ResourceManager.GetString("AdjustDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統函式 的當地語系化字串。
        /// </summary>
        internal static string AdminFunction {
            get {
                return ResourceManager.GetString("AdminFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統管理 的當地語系化字串。
        /// </summary>
        internal static string AdminManage {
            get {
                return ResourceManager.GetString("AdminManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 打卡及請假 的當地語系化字串。
        /// </summary>
        internal static string Attend {
            get {
                return ResourceManager.GetString("Attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 審核管理 的當地語系化字串。
        /// </summary>
        internal static string AuthenticationManage {
            get {
                return ResourceManager.GetString("AuthenticationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇調劑案件(案件分類) 的當地語系化字串。
        /// </summary>
        internal static string CaseCategoryNull {
            get {
                return ResourceManager.GetString("CaseCategoryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 慢箋請填寫調劑序號
        /// 的當地語系化字串。
        /// </summary>
        internal static string ChronicSeqError {
            get {
                return ResourceManager.GetString("ChronicSeqError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫領藥次數與總領藥次數
        /// 的當地語系化字串。
        /// </summary>
        internal static string ChronicTimesError {
            get {
                return ResourceManager.GetString("ChronicTimesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 慢箋請填寫可調劑次數
        /// 的當地語系化字串。
        /// </summary>
        internal static string ChronicTotalError {
            get {
                return ResourceManager.GetString("ChronicTotalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上下班打卡 的當地語系化字串。
        /// </summary>
        internal static string ClockIn {
            get {
                return ResourceManager.GetString("ClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合作診所藥品耗用 的當地語系化字串。
        /// </summary>
        internal static string CooperativeAdjustReport {
            get {
                return ResourceManager.GetString("CooperativeAdjustReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 部分負擔自費報表 的當地語系化字串。
        /// </summary>
        internal static string CooperativeEntry {
            get {
                return ResourceManager.GetString("CooperativeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫部分負擔
        /// 的當地語系化字串。
        /// </summary>
        internal static string CopaymentError {
            get {
                return ResourceManager.GetString("CopaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顧客管理 的當地語系化字串。
        /// </summary>
        internal static string CustomerManage {
            get {
                return ResourceManager.GetString("CustomerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 基本資料管理 的當地語系化字串。
        /// </summary>
        internal static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ..\Images\Done.png 的當地語系化字串。
        /// </summary>
        internal static string declareDone {
            get {
                return ResourceManager.GetString("declareDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ..\Images\Error.png 的當地語系化字串。
        /// </summary>
        internal static string declareError {
            get {
                return ResourceManager.GetString("declareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申報檔作業 的當地語系化字串。
        /// </summary>
        internal static string DeclareFile {
            get {
                return ResourceManager.GetString("DeclareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出申報檔 的當地語系化字串。
        /// </summary>
        internal static string DeclareFileExport {
            get {
                return ResourceManager.GetString("DeclareFileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ..\Images\SubmitProgress.png 的當地語系化字串。
        /// </summary>
        internal static string declareNone {
            get {
                return ResourceManager.GetString("declareNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫主診斷碼
        /// 的當地語系化字串。
        /// </summary>
        internal static string DiseaseCodeError {
            get {
                return ResourceManager.GetString("DiseaseCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無疾病代碼 的當地語系化字串。
        /// </summary>
        internal static string DiseaseCodeNotFound {
            get {
                return ResourceManager.GetString("DiseaseCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫就醫科別
        /// 的當地語系化字串。
        /// </summary>
        internal static string DivisionError {
            get {
                return ResourceManager.GetString("DivisionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 員工管理 的當地語系化字串。
        /// </summary>
        internal static string EmployeeManage {
            get {
                return ResourceManager.GetString("EmployeeManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存現值查詢 的當地語系化字串。
        /// </summary>
        internal static string EntrySearch {
            get {
                return ResourceManager.GetString("EntrySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 女 的當地語系化字串。
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得調劑案件... 的當地語系化字串。
        /// </summary>
        internal static string GetAdjustCases {
            get {
                return ResourceManager.GetString("GetAdjustCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得合作診所處方... 的當地語系化字串。
        /// </summary>
        internal static string GetCooperativePrescriptions {
            get {
                return ResourceManager.GetString("GetCooperativePrescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得部分負擔... 的當地語系化字串。
        /// </summary>
        internal static string GetCopayments {
            get {
                return ResourceManager.GetString("GetCopayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得科別... 的當地語系化字串。
        /// </summary>
        internal static string GetDivisions {
            get {
                return ResourceManager.GetString("GetDivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得釋出院所... 的當地語系化字串。
        /// </summary>
        internal static string GetInstitutions {
            get {
                return ResourceManager.GetString("GetInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得給付類別... 的當地語系化字串。
        /// </summary>
        internal static string GetPaymentCategories {
            get {
                return ResourceManager.GetString("GetPaymentCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得藥品途徑... 的當地語系化字串。
        /// </summary>
        internal static string GetPositions {
            get {
                return ResourceManager.GetString("GetPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得處方案件... 的當地語系化字串。
        /// </summary>
        internal static string GetPrescriptionCases {
            get {
                return ResourceManager.GetString("GetPrescriptionCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得特定治療代碼... 的當地語系化字串。
        /// </summary>
        internal static string GetSpecialTreats {
            get {
                return ResourceManager.GetString("GetSpecialTreats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得藥品用法... 的當地語系化字串。
        /// </summary>
        internal static string GetUsages {
            get {
                return ResourceManager.GetString("GetUsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處方作業 的當地語系化字串。
        /// </summary>
        internal static string hisPrescription {
            get {
                return ResourceManager.GetString("hisPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處方登錄 的當地語系化字串。
        /// </summary>
        internal static string hisPrescriptionDeclare {
            get {
                return ResourceManager.GetString("hisPrescriptionDeclare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處方查詢 的當地語系化字串。
        /// </summary>
        internal static string hisPrescriptionInquire {
            get {
                return ResourceManager.GetString("hisPrescriptionInquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image files (*.jpg;*.png)|*.jpg|All Files (*.*)|*.* 的當地語系化字串。
        /// </summary>
        internal static string ImageSelectorsFileTpyes {
            get {
                return ResourceManager.GetString("ImageSelectorsFileTpyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處方登錄成功 的當地語系化字串。
        /// </summary>
        internal static string InsertPrescriptionSuccess {
            get {
                return ResourceManager.GetString("InsertPrescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫釋出院所
        /// 的當地語系化字串。
        /// </summary>
        internal static string InstitutionError {
            get {
                return ResourceManager.GetString("InstitutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請假申請 的當地語系化字串。
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 櫃位管理 的當地語系化字串。
        /// </summary>
        internal static string LocationManage {
            get {
                return ResourceManager.GetString("LocationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 男 的當地語系化字串。
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 供應商管理 的當地語系化字串。
        /// </summary>
        internal static string ManufactoryManage {
            get {
                return ResourceManager.GetString("ManufactoryManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 藥袋管理 的當地語系化字串。
        /// </summary>
        internal static string MedBagManage {
            get {
                return ResourceManager.GetString("MedBagManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 藥袋列印中... 的當地語系化字串。
        /// </summary>
        internal static string MedBagPrinting {
            get {
                return ResourceManager.GetString("MedBagPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 藥品頻率管理 的當地語系化字串。
        /// </summary>
        internal static string MedFrequencyManage {
            get {
                return ResourceManager.GetString("MedFrequencyManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫就醫序號
        /// 的當地語系化字串。
        /// </summary>
        internal static string MedicalNumberError {
            get {
                return ResourceManager.GetString("MedicalNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫就醫序號
        /// 的當地語系化字串。
        /// </summary>
        internal static string MedicalNumberError1 {
            get {
                return ResourceManager.GetString("MedicalNumberError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日劑藥費且為西醫一般案件，給藥日份不得超過3天 的當地語系化字串。
        /// </summary>
        internal static string MedicineDaysOutOfRange {
            get {
                return ResourceManager.GetString("MedicineDaysOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一般處方箋給藥日份不得超過7天 的當地語系化字串。
        /// </summary>
        internal static string MedicineDaysOutOfRange_1_7 {
            get {
                return ResourceManager.GetString("MedicineDaysOutOfRange_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫處方藥品
        /// 的當地語系化字串。
        /// </summary>
        internal static string MedicineEmpty {
            get {
                return ResourceManager.GetString("MedicineEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無藥品 的當地語系化字串。
        /// </summary>
        internal static string MedicineNotFound {
            get {
                return ResourceManager.GetString("MedicineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增盤點 的當地語系化字串。
        /// </summary>
        internal static string NewStockTaking {
            get {
                return ResourceManager.GetString("NewStockTaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫給付類別
        /// 的當地語系化字串。
        /// </summary>
        internal static string PaymentCategoryError {
            get {
                return ResourceManager.GetString("PaymentCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選擇調劑藥師或調劑藥師身分證未填寫\n 的當地語系化字串。
        /// </summary>
        internal static string PharmacistIDError {
            get {
                return ResourceManager.GetString("PharmacistIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 藥局管理 的當地語系化字串。
        /// </summary>
        internal static string PharmacyManage {
            get {
                return ResourceManager.GetString("PharmacyManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇處方案件
        /// 的當地語系化字串。
        /// </summary>
        internal static string PrescriptionCaseError {
            get {
                return ResourceManager.GetString("PrescriptionCaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處方已超過可領取時限
        /// 的當地語系化字串。
        /// </summary>
        internal static string PrescriptoinOutOfDate {
            get {
                return ResourceManager.GetString("PrescriptoinOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印確認 的當地語系化字串。
        /// </summary>
        internal static string PrintConfirm {
            get {
                return ResourceManager.GetString("PrintConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否列印藥袋 的當地語系化字串。
        /// </summary>
        internal static string PrintMedBag {
            get {
                return ResourceManager.GetString("PrintMedBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否列印收據 的當地語系化字串。
        /// </summary>
        internal static string PrintReceipt {
            get {
                return ResourceManager.GetString("PrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進退貨管理 的當地語系化字串。
        /// </summary>
        internal static string ProductPurchase {
            get {
                return ResourceManager.GetString("ProductPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進退貨紀錄 的當地語系化字串。
        /// </summary>
        internal static string ProductPurchaseRecord {
            get {
                return ResourceManager.GetString("ProductPurchaseRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品類別管理 的當地語系化字串。
        /// </summary>
        internal static string ProductTypeManage {
            get {
                return ResourceManager.GetString("ProductTypeManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進退貨報表查詢 的當地語系化字串。
        /// </summary>
        internal static string PurchaseReturnReport {
            get {
                return ResourceManager.GetString("PurchaseReturnReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收據列印中... 的當地語系化字串。
        /// </summary>
        internal static string ReceiptPrinting {
            get {
                return ResourceManager.GetString("ReceiptPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報表系統 的當地語系化字串。
        /// </summary>
        internal static string ReportSystem {
            get {
                return ResourceManager.GetString("ReportSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢日期範圍超出限制(3個月) 的當地語系化字串。
        /// </summary>
        internal static string SearchDateOutOfRange {
            get {
                return ResourceManager.GetString("SearchDateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋字長度不得小於 的當地語系化字串。
        /// </summary>
        internal static string ShortSearchString {
            get {
                return ResourceManager.GetString("ShortSearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫起始日期 的當地語系化字串。
        /// </summary>
        internal static string StartDateEmpty {
            get {
                return ResourceManager.GetString("StartDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起始日期不得大於結束日期 的當地語系化字串。
        /// </summary>
        internal static string StartDateOutOfRange {
            get {
                return ResourceManager.GetString("StartDateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品管理 的當地語系化字串。
        /// </summary>
        internal static string StockManage {
            get {
                return ResourceManager.GetString("StockManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品查詢 的當地語系化字串。
        /// </summary>
        internal static string StockSearch {
            get {
                return ResourceManager.GetString("StockSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存盤點 的當地語系化字串。
        /// </summary>
        internal static string StockTaking {
            get {
                return ResourceManager.GetString("StockTaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存盤點紀錄 的當地語系化字串。
        /// </summary>
        internal static string StockTakingRecord {
            get {
                return ResourceManager.GetString("StockTakingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫就醫日期\n 的當地語系化字串。
        /// </summary>
        internal static string TreatDateError {
            get {
                return ResourceManager.GetString("TreatDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排班管理 的當地語系化字串。
        /// </summary>
        internal static string WorkScheduleManage {
            get {
                return ResourceManager.GetString("WorkScheduleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;? xml version = &quot;1.0&quot; encoding = &quot;Big5&quot; ?&gt; 的當地語系化字串。
        /// </summary>
        internal static string XmlDeclare {
            get {
                return ResourceManager.GetString("XmlDeclare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與健保局連線認證中，請稍後... 的當地語系化字串。
        /// </summary>
        internal static string 健保局連線中 {
            get {
                return ResourceManager.GetString("健保局連線中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卡片資料與目前顧客資訊不符，
        ///是否覆蓋? 的當地語系化字串。
        /// </summary>
        internal static string 卡片資料不符 {
            get {
                return ResourceManager.GetString("卡片資料不符", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得就醫序號... 的當地語系化字串。
        /// </summary>
        internal static string 取得就醫序號 {
            get {
                return ResourceManager.GetString("取得就醫序號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 口服液劑(原瓶包裝) 的當地語系化字串。
        /// </summary>
        internal static string 口服液劑 {
            get {
                return ResourceManager.GetString("口服液劑", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卡片資料寫入中... 的當地語系化字串。
        /// </summary>
        internal static string 寫卡 {
            get {
                return ResourceManager.GetString("寫卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卡片寫入異常，請選擇異常代碼 的當地語系化字串。
        /// </summary>
        internal static string 寫卡異常 {
            get {
                return ResourceManager.GetString("寫卡異常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 所置入非安全模組卡(檔) 的當地語系化字串。
        /// </summary>
        internal static string 所置入非安全模組 {
            get {
                return ResourceManager.GetString("所置入非安全模組", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 押金確認 的當地語系化字串。
        /// </summary>
        internal static string 押金確認 {
            get {
                return ResourceManager.GetString("押金確認", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀卡機控制軟體異常，請檢查讀卡機設備 的當地語系化字串。
        /// </summary>
        internal static string 控制軟體異常 {
            get {
                return ResourceManager.GetString("控制軟體異常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未認證 的當地語系化字串。
        /// </summary>
        internal static string 未認證 {
            get {
                return ResourceManager.GetString("未認證", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查中... 的當地語系化字串。
        /// </summary>
        internal static string 檢查中 {
            get {
                return ResourceManager.GetString("檢查中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 健保IC卡檢查中... 的當地語系化字串。
        /// </summary>
        internal static string 檢查健保卡 {
            get {
                return ResourceManager.GetString("檢查健保卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 安全模組檢查中... 的當地語系化字串。
        /// </summary>
        internal static string 檢查安全模組 {
            get {
                return ResourceManager.GetString("檢查安全模組", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 醫事人員卡檢查中... 的當地語系化字串。
        /// </summary>
        internal static string 檢查醫事人員卡 {
            get {
                return ResourceManager.GetString("檢查醫事人員卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生每日上傳資料中... 的當地語系化字串。
        /// </summary>
        internal static string 產生每日上傳資料 {
            get {
                return ResourceManager.GetString("產生每日上傳資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合作診所處方不可登錄，
        ///請將調劑日期設定為今天 的當地語系化字串。
        /// </summary>
        internal static string 登錄合作診所處方 {
            get {
                return ResourceManager.GetString("登錄合作診所處方", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請確認處方病患資訊與健保卡資訊符合 的當地語系化字串。
        /// </summary>
        internal static string 確認卡片 {
            get {
                return ResourceManager.GetString("確認卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認證失敗 的當地語系化字串。
        /// </summary>
        internal static string 認證失敗 {
            get {
                return ResourceManager.GetString("認證失敗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認證成功 的當地語系化字串。
        /// </summary>
        internal static string 認證成功 {
            get {
                return ResourceManager.GetString("認證成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認證成功(已驗PIN) 的當地語系化字串。
        /// </summary>
        internal static string 認證成功已驗 {
            get {
                return ResourceManager.GetString("認證成功已驗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 認證成功(未驗PIN) 的當地語系化字串。
        /// </summary>
        internal static string 認證成功未驗 {
            get {
                return ResourceManager.GetString("認證成功未驗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀卡機異常，請重置讀卡機，若仍異常，請重開電源再重置一次，如持續異常，請檢查傳輸線或讀卡機設備是否正確連接或有損壞 的當地語系化字串。
        /// </summary>
        internal static string 讀卡機異常 {
            get {
                return ResourceManager.GetString("讀卡機異常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀卡機逾時 的當地語系化字串。
        /// </summary>
        internal static string 讀卡機逾時 {
            get {
                return ResourceManager.GetString("讀卡機逾時", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 健保卡資料讀取中... 的當地語系化字串。
        /// </summary>
        internal static string 讀取健保卡 {
            get {
                return ResourceManager.GetString("讀取健保卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 健保卡讀取失敗 的當地語系化字串。
        /// </summary>
        internal static string 讀取失敗 {
            get {
                return ResourceManager.GetString("讀取失敗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 健保卡讀取成功 的當地語系化字串。
        /// </summary>
        internal static string 讀取成功 {
            get {
                return ResourceManager.GetString("讀取成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料不符 的當地語系化字串。
        /// </summary>
        internal static string 資料不符 {
            get {
                return ResourceManager.GetString("資料不符", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀卡機連接開啟失敗 的當地語系化字串。
        /// </summary>
        internal static string 連接失敗 {
            get {
                return ResourceManager.GetString("連接失敗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀卡機連接開啟成功 的當地語系化字串。
        /// </summary>
        internal static string 連接成功 {
            get {
                return ResourceManager.GetString("連接成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未選擇異常代碼，請輸入押金金額或重新過卡後再次按下調劑按鈕 的當地語系化字串。
        /// </summary>
        internal static string 重新過卡或押金 {
            get {
                return ResourceManager.GetString("重新過卡或押金", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀卡機重置中... 的當地語系化字串。
        /// </summary>
        internal static string 重置讀卡機 {
            get {
                return ResourceManager.GetString("重置讀卡機", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開啟讀卡機連接... 的當地語系化字串。
        /// </summary>
        internal static string 開啟讀卡機 {
            get {
                return ResourceManager.GetString("開啟讀卡機", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 醫事人員卡驗證中... 的當地語系化字串。
        /// </summary>
        internal static string 驗證醫事人員卡 {
            get {
                return ResourceManager.GetString("驗證醫事人員卡", resourceCulture);
            }
        }
    }
}
